// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3dRSEoKwKO_I8UDJtjU--zRPy-81CFE0',
    appId: '1:41391582376:android:ee8a43fdbfc071066b669d',
    messagingSenderId: '41391582376',
    projectId: 'parentapp-b2d34',
    databaseURL: 'https://parentapp-b2d34.firebaseio.com',
    storageBucket: 'parentapp-b2d34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbYpVxGRDuCZg1RTyoDHzn4AGKxtGO1N4',
    appId: '1:41391582376:ios:7c27c40c2a12c2b06b669d',
    messagingSenderId: '41391582376',
    projectId: 'parentapp-b2d34',
    databaseURL: 'https://parentapp-b2d34.firebaseio.com',
    storageBucket: 'parentapp-b2d34.appspot.com',
    androidClientId: '41391582376-1d3qo4h7qaoteeu9i8ufhtkf6idskjnm.apps.googleusercontent.com',
    iosClientId: '41391582376-1q0sih7h2juauabvl7jrc8k97epiqpm5.apps.googleusercontent.com',
    iosBundleId: 'com.parents.parentsAppFlutter',
  );
}
